version: '2'
services:
  production-server:
    container_name: production-server
    build:
      context: .
      dockerfile: Dockerfile
    image: dev-rss-parser:latest
    ports:
      - 19900-19999:8080
    networks:
      - spring-cloud-network